compiler : gcc

                   dist : xenial

                                  language : C script : -git ls
                                                        - files src /
        | xargs clang - format - i&& git diff â€”exit - code&& make
